### ISSUE TITLE
多重嵌套的对象能存，但解析不了

### ISSUE THREAD

**Issue by hjpraul** [huangzhibiao/BGFMDB#1]
直接看截图，是在您最新的demo上作了一点点小修改：
![image](https://cloud.githubusercontent.com/assets/5102014/24501513/65a7ede4-157c-11e7-9f52-2ed4868fb803.png)

**Comment by huangzhibiao** [comment]
OK，我明天看看

**Comment by huangzhibiao** [comment]
由于之前修改代码时疏忽造成的，已经解决,请更新到最新版的代码.

**Comment by 985317733** [comment]
最近在使用这个框架,把解析与存储结合起来,非常人性化,
关于字典转模型,有几个小的建议:

1.增加替换变量的功能,如:
+ (NSDictionary *)mj_replacedKeyFromPropertyName {
    return @{@"addressId":@"id"};
}

2.增加一个字典数组转模型数组功能,如-mj_objectArrayWithKeyValuesArray:  (解析时可选存储更好)
