### ISSUE TITLE
插入100条数据有点慢

### ISSUE THREAD

**Issue by Wbqqqq** [huangzhibiao/BGFMDB#11]
目前  我有100条model数据  for循环插入要2秒左右的时间 这个太久了  有什么一下子插入100条的数据吗

for (YLHomeCardModel *model in reversedArray) {
                
                model.updateTime = [Utility currentTimeInterval];
                
                [model bg_saveOrUpdate];
                
                NSLog(@"update name %@ date %@",model.title,model.updateTime);
            }

**Comment by huangzhibiao** [comment]
批量插入用以下API:
/**
 同步存入对象数组.
 @array 存放对象的数组.(数组中存放的是同一种类型的数据)
 */
+(BOOL)bg_saveArray:(NSArray* _Nonnull)array IgnoreKeys:(NSArray* const _Nullable)ignoreKeys;

或你自己启动事物操作:
  [NSObject bg_inTransaction:^BOOL{
       for (YLHomeCardModel *model in reversedArray) {
            model.updateTime = [Utility currentTimeInterval];
            [model bg_saveOrUpdate];
            NSLog(@"update name %@ date %@",model.title,model.updateTime);
        }
        return YES;
    }];

这样批量插入就一下子OK了，不然你每插入一条要提交一次，批量这样插入肯定就慢了.

**Comment by huangzhibiao** [comment]
如果类定义了唯一约束，你就用这个API：
/**
 同步存储或更新数组.
 当自定义“唯一约束”时可以使用此接口存储更方便,当"唯一约束"的数据存在时，此接口会更新旧数据,没有则存储新数据.
 */
+(void)bg_saveOrUpdateArray:(NSArray* _Nonnull)array IgnoreKeys:(NSArray* const _Nullable)ignoreKeys;
