### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by firenessZX** [huangzhibiao/BGFMDB#12]
![822c5955-ba6a-4f5a-b829-c16709bb0ba1](https://user-images.githubusercontent.com/15721984/30734021-0f808556-9fac-11e7-91d2-6605519618ed.png)

**Comment by huangzhibiao** [comment]
你不要直接调用BGFMDB.h里面的api，调BGModel+NSObject.h里面的API（这里的API才是对外提供的）
