### ISSUE TITLE
按时间删除不能成功

### ISSUE THREAD

**Issue by huangxiaojieCoder** [huangzhibiao/BGFMDB#15]
[OTWaitOrderModel bg_deleteFormatSqlConditions:@"where %@ like %@",bg_sqlKey(bg_createTimeKey),@"2017-09-27 19:57:38"];

**Comment by huangxiaojieCoder** [comment]
成功了时间格式输入错误了，正确应该是
 [OTWaitOrderModel bg_deleteFormatSqlConditions:@"where %@ like %@",bg_sqlKey(bg_createTimeKey),@"'2017-09-27 19:57:38%'"];

**Comment by huangzhibiao** [comment]
OK
