### ISSUE TITLE
多线程事务操作

### ISSUE THREAD

**Issue by iosApem** [huangzhibiao/BGFMDB#16]
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,0), ^{
            NSLog(@"存储...");
            bg_inTransaction(^BOOL{
                return [p bg_save];
           });
 });

这样会出现
The FMDatabase <FMDatabase: 0x6000000a3c60> is currently in use.

**Comment by huangzhibiao** [comment]
事物你先用同步，因为异步事物会和其他线程的增删改查操作发生冲突

**Comment by iosApem** [comment]
我们现在的需求就是要在事务里执行多个数据库操作, 而你的库现在暂时还不支持
我已经找到方法了:
这个方法使用递归锁
- (void)executeDB:(void (^)(FMDatabase *db))block

**Comment by huangzhibiao** [comment]
ok

**Comment by huangzhibiao** [comment]
不过在这里加锁会有点影响性能，因为其他操作都会执行这个函数.

**Comment by huangzhibiao** [comment]
而且如果同时执行多个

dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,0), ^{
NSLog(@"存储...");
bg_inTransaction(^BOOL{
return [p bg_save];
});
});

时也还有出现问题.

**Comment by huangzhibiao** [comment]
我已经找到一个解决方案了，在github上下载最新源码测试，pod我稍后上传。

你在(void)executeDB:(void (^)(FMDatabase *db))block这个方法里加递归锁的话，如果同时有多个异步事务或同时还有其他增删改查操作的话会发生busy或线程冲突，

**Comment by huangzhibiao** [comment]
还有什么问题及时反馈.

**Comment by iosApem** [comment]
暂时没有了
