### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by sunsx9316** [huangzhibiao/BGFMDB#17]
BGProtocol协议建议增加类似黑名单 白名单的接口 固定不解析/解析某些属性
1. 黑名单里的属性不进行存储操作
2. 如果设置了白名单的属性 则只存储白名单的属性
因为对于某些固定忽略属性IgnoreKeys每次存储都需要设置 而对于属性很多 但是只更新少量变量的类 又需要写很多的IgnoreKeys 或者写麻烦的sql语句

**Comment by huangzhibiao** [comment]
这个问题我先前已经注意到了，我一开始设计考虑的是初学者的直观性，但是到后面发现这样的确不太好，造成API冗长，但是想要改的时候发现牵动的地方比较多了，所以就搁置了，你可以先把IgnoreKeys的数组定义成一个宏或全局的变量，这样相对而言就好多了，我后面有时间再重构了，不过还是谢谢你的建议☺.

**Comment by huangzhibiao** [comment]
下个版本我会考虑修改，从最外层取代IgnoreKeys数组应该是蛮快的.

**Comment by yangguang66** [comment]
你的cocoapods代买是1.4.4本的，没有更新到最新版本。

**Comment by yangguang66** [comment]
你的fmdb不会直接更新是吧？？？？你版fmdb封装在你的项目中了。。

**Comment by huangzhibiao** [comment]
什么意思？我最近进行了大重构，有些API变化比较大(你更新的时候注意些,如果旧版本能满足你的需求，那就不要更新了)，因为之前的API有些冗余了，所以优化缩减了，同时更加了你建议的功能，和表名自定义功能等.

**Comment by yangguang66** [comment]
用1.4.4就可以了是吗？    我你封装的是FMDB，如果FMDB更新了，你的这个库里面的FMDB不会更新。那我可要用到项目中了。感觉你写的很不错。

**Comment by yangguang66** [comment]
你的新版本在cocoapods什么时候能够更新，我现在正在寻找好用的封装，不想自己写。

**Comment by yangguang66** [comment]
朋友加个好友好吗？2451964239 我的qq号

**Comment by huangzhibiao** [comment]
572359447这是使用交流群,FMDB现在基本稳定了，如果有什么大更新，我会更新FMDB到我的库，你只管更新我的库就OK了，不需要管FMDB.

**Comment by huangzhibiao** [comment]
最新版本过一阵子再更新到cocoapods, 大家都在测试使用中, 因为我大重构可能会有忽漏的bug,等过些天大家都使用OK了,我再更新到cocoapods.

**Comment by myDonghao** [comment]
就是两个类互为对方属性的时候，会出现死循环？ 我用的是旧版本的，没有用最新版，如果作者大大已经解决了，请忽略。

**Comment by huangzhibiao** [comment]
是的，两个类不能互为属性，不然会出现解析死循环.

**Comment by huangzhibiao** [comment]
是的，两个类不能互为属性，否则会出现解析死循环.
