### ISSUE TITLE
关于用cocoapads集成您这个库，只要调用“bg_setDebug，bg_setSqliteName，bg_setDisableCloseDB”方法就报错，不用这几个方法就没问题，各种配置都无效

### ISSUE THREAD

**Issue by FlyingAppleFish** [huangzhibiao/BGFMDB#18]
clang: warning: libstdc++ is deprecated; move to libc++ [-Wdeprecated]
clang: warning: libstdc++ is deprecated; move to libc++ [-Wdeprecated]
Undefined symbols for architecture arm64:
  "bg_setDebug(bool)", referenced from:
      -[TestViewController viewDidLoad] in TestViewController.o
  "bg_setDisableCloseDB(bool)", referenced from:
      -[TestViewController viewDidLoad] in TestViewController.o
  "bg_setSqliteName(NSString*)", referenced from:
      -[TestViewController viewDidLoad] in TestViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by FlyingAppleFish** [comment]
另外，您这个库，每次存了3000条就存不了了，大概229k，这是指单次运行中，只能存229k，关闭应用重新开启可以继续存229k，如何能不关闭应用一直存呢

**Comment by huangzhibiao** [comment]
遵照demo的配置即可，ibstdc++用libc++代替（要阅读英文，不懂就翻译）.
库存储容量没有限制，肯定是你处理的不对，贴出你的使用代码。

**Comment by FlyingAppleFish** [comment]
建了个新工程，没有上述问题了，可能是老工程配置出了问题，感谢作者耐心解答
