### ISSUE TITLE
Can't check

### ISSUE THREAD

**Issue by gyyxiaogao** [huangzhibiao/BGFMDB#20]
![snip20171227_3](https://user-images.githubusercontent.com/16957066/34374174-a50b3170-eb1a-11e7-925c-957f19e54d29.png)

**Comment by huangzhibiao** [comment]
要用bg_sqlValue(@"YFB"); 包住.

**Comment by gyyxiaogao** [comment]
嗯啦,可以了,为啥有的不需要包住?

**Comment by huangzhibiao** [comment]
key和value，你分别用bg_sqlKey()和bg_sqlValue()包住就OK了，想知道为啥就看一下源码.

**Comment by gyyxiaogao** [comment]
嗯啦,我刚看了一下我存的数据,明白了,谢谢.
