### ISSUE TITLE
嗯哼

### ISSUE THREAD

**Issue by wangrui460** [huangzhibiao/BGFMDB#21]
pod 'BGFMDB', '~> 2.0.2'  在哪呢？

s.name         = "BGFMDB"
s.version      = "2.0.1"
s.summary      = "完美支持iOS大部分类型数据的存储,同时带有 字典转模型 功能模块."

**Comment by huangzhibiao** [comment]
更新一下pod缓存，pod repo update

**Comment by wangrui460** [comment]
你的 BGFMDB.podspec 文件没有更新， s.version 还是 "2.0.1"

**Comment by huangzhibiao** [comment]
这个文件的最新版我没有更新到github上，你在终端pod repo update,然后pod search BGFMDB就看到了.
