### ISSUE TITLE
请问这是什么问题 有的手机上出现了这个 而且出现概率还不低

### ISSUE THREAD

**Issue by 321zhangyang** [huangzhibiao/BGFMDB#22]
select * from UCState where BG_isLoggedIn = 1
 [logging] file is encrypted or is not a database
 DB Error: 26 "file is encrypted or is not a database"
 DB Query: select * from UCState where BG_isLoggedIn = 1

**Comment by huangzhibiao** [comment]
你这个是不是很旧之前的版本了?   之前的数据库不是以.db为后缀名，所以会出现这个提示。
你更新到最新版本吧.

**Comment by zgs2046** [comment]
有这样的需求，有一个TestModel，带有10个属性，其中，有一个属性是可变数组，初始化时，可变数组是空数组或者有一个自定义的SubTestModel或者UIImage，但是当用户操作以后，可变数组中需要增加或者删除数个SubTestModel或者UIImage，用bg_update:bg_tablename where:where方法，会数据库报错：near "XXX": syntax error，看了你的所有方法，没有找到明确的提示，还请你有时间帮忙看看，因为这种可变数组更新对于那种可选择图片然后离线保存，下一次在提交后台前又可以操作之前离线保存的数据的应用还是很常见的操作。另外，作者辛苦了，佩服作者的开源精神和奉献精神。给你加星了，汗颜我这个拿来主义狗第一次给开源作者加星。
