### ISSUE TITLE
模型属性是可变数组更新的问题

### ISSUE THREAD

**Issue by zgs2046** [huangzhibiao/BGFMDB#23]
有这样的需求，有一个TestModel，带有10个属性，其中，有一个属性是可变数组，初始化时，可变数组是空数组或者有一个自定义的SubTestModel或者UIImage，但是当用户操作以后，可变数组中需要增加或者删除数个SubTestModel或者UIImage，用bg_update:bg_tablename where:where方法，会数据库报错：near "XXX": syntax error，看了作者的所有方法，没有找到明确的提示，还请作者有时间帮忙看看，因为这种可变数组更新对于那种可选择图片然后离线保存，下一次在提交后台前又可以操作之前离线保存的数据的应用还是很常见的操作。另外，作者辛苦了，佩服作者的开源精神和奉献精神。给你加星了，汗颜我这个拿来主义狗第一次给开源作者加星。

**Comment by huangzhibiao** [comment]
贴出你的使用代码我看看

**Comment by zgs2046** [comment]
BOOL success = [strongSelf updatePropertyInDB:@"chosedPicsArray" Value:strongSelf.model.chosedPicsArray];
                if (success) {
                    NSLog(@"更新数组成功");
                }else{
                    NSLog(@"更新数组失败");
                }

-(BOOL)updatePropertyInDB:(NSString *)property Value:(id)value{
    NSString * update = [NSString stringWithFormat:@"set %@=%@ where %@=%@",bg_sqlKey(property),bg_sqlValue(value),bg_sqlKey(@"ROWINDEX"),bg_sqlValue(@(self.model.ROWINDEX))];
    return [TestModel bg_update:nil where:update];
}
这个chosedPicsArray，是一个试题模型的可变数组，里面存的是自定义模型，这个自定义模型存储的是图片名和地址信息（可能是本地沙盒地址，也可能是网络图片地址），ROWINDEX对应的是该题目对应的编号。我们这个项目是答题类项目，试题中每道题用户可选则最多五张图片，可增可删

**Comment by huangzhibiao** [comment]
我知道问题所在了，稍后就解决，谢谢你的反馈.

**Comment by huangzhibiao** [comment]
问题已经解决了，最新代码已上传，版本号：2.0.3

**Comment by zgs2046** [comment]
好的，谢了！向你学习！
