### ISSUE TITLE
原表数据重新创建表插入数据的问题

### ISSUE THREAD

**Issue by zgs2046** [huangzhibiao/BGFMDB#26]
还是那个答题类的项目引出的问题：比如50道题，用bg_saveOrUpdateArray方法存储，模型的bg_tableName赋值为@“questionTable”，用户全部答完，答对了40道，错了10道，用户选择交卷以后，进入一个选择结果的界面，该页面有“查看本次对题”，“查看本次错题”的选项，这时如果用户选择查看错题，我需要从原来的表中查询出这10道题，对这10道题再存入一个错题的表中，用于后继的连续性显示的需要，我用的是依然是bg_saveOrUpdateArray这个方法，只不过，这10道题对应的模型的bg_tableName重新赋值为比如叫@“wrongTable”，这时发现wrongTable表创建成功，但是数据无法插入，大概跟了一下，发现是bgdb.m中-(void)bg_saveOrUpdateWithTableName:(NSString* _Nonnull)tablename class:(__unsafe_unretained _Nonnull Class)cla DictArray:(NSArray<NSDictionary*>* _Nonnull)dictArray complete:(bg_complete_B)complete，对于isSave的判断走了([tempDict.allKeys containsObject:bg_id])这个分支，所以最终本来应该是要做的存储操作变成了更新操作，最后wrongTable中始终没有数据。是我没有正确的使用吗？***另外，有没有提供按条件查询属性值的方法，我找了一下，没有找到，比如，我只是单纯地想要查询某一道题题目id为0002的题目对应的答题结果这个属性是答对还是答错，得到一个id类型的值，这时就没有必要查出一条完整的数据。望帮忙指正，谢谢！

**Comment by huangzhibiao** [comment]
你这个业务逻辑是属于个人问题，不好为了个人业务改掉修改库，目前先给你的建议是把那10道题的bg_id设为nil后，再存入到wrongTable表中即可。

至于只想查询某个属性的话，你可以自己再封装一层即可,库之所以叫库就是在满足大部分人需求的基础上，又能尽量地保持简洁.

**Comment by zgs2046** [comment]
已经搞定了，谢谢了
