### ISSUE TITLE
这个好像取不出来 一直报空的错误

### ISSUE THREAD

**Issue by z724211471** [huangzhibiao/BGFMDB#27]
//转换从数据库中读取出来的数据.
+(NSArray*)tansformDataFromSqlDataWithTableName:(NSString*)tableName class:(__unsafe_unretained _Nonnull Class)cla array:(NSArray*)array{
    NSMutableArray* arrM = [NSMutableArray array];
    for(NSDictionary* dict in array){
        id object = [BGTool objectFromJsonStringWithTableName:tableName class:cla valueDict:dict];
        [arrM addObject:object];
    }
    return arrM;
}

**Comment by huangzhibiao** [comment]
贴出你的使用代码

**Comment by z724211471** [comment]
NSMutableArray *ss=bg_executeSql(@"select BG_iconid from usericon",@"usericon",nil);

**Comment by huangzhibiao** [comment]
最后那个参数要传入你所对应的类

**Comment by z724211471** [comment]
@cla 要操作的类,nil时返回的结果是字典.  不是nil返回的结果是字典吗

**Comment by huangzhibiao** [comment]
不是nil时返回的是你传入的类对象实例

**Comment by z724211471** [comment]
如果我想我的结果 按照字典来显示     NSMutableArray *ss=bg_executeSql(@"select * from usericon ",@"usericon",[usericon class]); 我用这个还要遍历去取哦

**Comment by huangzhibiao** [comment]
//转换从数据库中读取出来的数据.
+(NSArray*)tansformDataFromSqlDataWithTableName:(NSString*)tableName class:(__unsafe_unretained _Nonnull Class)cla array:(NSArray*)array{
    NSMutableArray* arrM = [NSMutableArray array];
    for(NSDictionary* dict in array){
        id object = [BGTool objectFromJsonStringWithTableName:tableName class:cla valueDict:dict];
        [arrM addObject:object];
    }
    return arrM;
}

你把这个函数改成：

//转换从数据库中读取出来的数据.
+(NSArray*)tansformDataFromSqlDataWithTableName:(NSString*)tableName class:(__unsafe_unretained _Nonnull Class)cla array:(NSArray*)array{
   if(cla == nil){
        return array;
   }
    NSMutableArray* arrM = [NSMutableArray array];
    for(NSDictionary* dict in array){
        id object = [BGTool objectFromJsonStringWithTableName:tableName class:cla valueDict:dict];
        [arrM addObject:object];
    }
    return arrM;
}

最后一个参数为nil时返回的就是字典了.

**Comment by z724211471** [comment]
好的 多谢🙏
