### ISSUE TITLE
请问,为什么要固定存储字典的Table名呢

### ISSUE THREAD

**Issue by ChandHsu** [huangzhibiao/BGFMDB#29]
比如我要存很多种字典,都要放进这个基础的字典里更新,和数组一样独立设置应该更方便,或者有其他高明的使用方法,新手请指教

**Comment by huangzhibiao** [comment]
字典你只关心key即可,key不同就可以错别开了，如果想再区别一层，那在字典里再存一层字典即可.

**Comment by ChandHsu** [comment]
如果我用来存消息记录,成百上千条存到这个字典里面,读取的时候会不会把整个字典读取到内存,造成内存暴涨呢?

**Comment by huangzhibiao** [comment]
存消息最好存到不同的表中，使用模型自定义表名.bg_tableName

**Comment by ChandHsu** [comment]
用消息的模型直接存吗,谢谢,我试试
