### ISSUE TITLE
关于字典转模型,有几个小的建议:

### ISSUE THREAD

**Issue by 985317733** [huangzhibiao/BGFMDB#3]
最近在使用这个框架,把解析与存储结合起来,非常人性化,
关于字典转模型,有几个小的建议:

1.增加替换变量的功能,如:

(NSDictionary *)mj_replacedKeyFromPropertyName {
return @{@"addressId":@"id"};
}
2.增加一个字典数组转模型数组功能,如-mj_objectArrayWithKeyValuesArray: (解析时可选存储更好)

**Comment by huangzhibiao** [comment]
最新增加了这两个小功能.
