### ISSUE TITLE
如果你能写一个使用BGFMDB的demo的话，就更好了。

### ISSUE THREAD

**Issue by wenjing0628** [huangzhibiao/BGFMDB#30]
你的这个BGFMDB像你说的很好用，但是网上一搜索，发现使用你的框架写的demo却一个都没有，即时一个懂FMDB的人，想用您的框架。还要重新学习，比较花费时间。我就是提个建议！望采纳！！！！

**Comment by huangzhibiao** [comment]
github上的使用例子就是demo,下载下来运行即可.
