### ISSUE TITLE
关于嵌套基类模型的问题

### ISSUE THREAD

**Issue by ChandHsu** [huangzhibiao/BGFMDB#32]
有这样一种情况:
我存储的ECMessage模型里面有一个ECMessageBody,这个ECMessageBody是作为基类存在的,也就是说真实的情况会是继承自ECMessageBody的ECTextMessageBody,ECVideoMessageBody等等,在存储的时候,存成了ECMessageBody造成了数据的丢失和无法还原.
这个问题该怎么解决呢?

**Comment by huangzhibiao** [comment]
目前只能根据属性固定的具体类型去解析，然后执行存储操作，子类对象指向父类指针的话需要解析对象的真实类型，我后面再看一下有没有好的决定方案.

**Comment by huangzhibiao** [comment]
问题解决了，已上传至github，你下载最新源码测试使用下，有问题及时反馈给我,pod我稍后上传.

**Comment by ChandHsu** [comment]
已经测试,可以了,谢谢大牛

**Comment by ChandHsu** [comment]
已经测试了,现在遇到了新的问题:
在App未关闭的情况下,当前生命周期存储的对象是可以正常解析的;
杀死app之后,再进入app读取历史数据就会报之前的错了

**Comment by huangzhibiao** [comment]
错误信息是什么？贴出来

**Comment by ChandHsu** [comment]
![8022509b-bad0-4db2-8491-552a73c930ac](https://user-images.githubusercontent.com/10771362/36766443-e3ec2264-1c70-11e8-8c3d-fa360579d7be.png)

**Comment by huangzhibiao** [comment]
我大概知道什么问题了

**Comment by huangzhibiao** [comment]
解决了，重新下载github最新源码测试一下,有问题及时反馈给我.

**Comment by huangzhibiao** [comment]
你先卸载APP后重装，再测，因为修改后,数据的编码有变化，旧的数据无法解析.

**Comment by ChandHsu** [comment]
好的，谢谢大牛，因为家里有急事，几天以后才能测，到时候有问题了我再反馈

**Comment by vitasapple** [comment]
请问要怎么做模糊搜索？我有好多个字段，nickname，phone,remark要怎么做

**Comment by huangzhibiao** [comment]
跟使用sqlite的like一样，具体使用百度sqlite的like使用方式即可

**Comment by vitasapple** [comment]
我看了demo，用bg_executeSql可以用sql语句，但是SELECT * FROM GoodsTab WHERE BG_nickName LIKE '%%%@%%'这个可以对nickname做模糊搜索，但是如果变成SELECT * FROM GoodsTab WHERE BG_nickName LIKE '%%%@%%' OR BG_goodsName LIKE '%%%@%%'就返回空数组，大佬知道怎么对多个字段搜索吗

**Comment by vitasapple** [comment]
解决了，谢谢大佬

**Comment by huangzhibiao** [comment]
没有明白你的意思

**Comment by ChandHsu** [comment]
就是又嵌套了一层,又出现了上面的错误

**Comment by huangzhibiao** [comment]
我稍后再看一下

**Comment by ChandHsu** [comment]
好的,有劳大神

**Comment by huangzhibiao** [comment]
这个问题已完美解决,已上传到pod，更新到2.0.6版本即可.

**Comment by ChandHsu** [comment]
已测试,完美👍👍👍
