### ISSUE TITLE
在使用 uniqueKeys 是否有編譯順序之差

### ISSUE THREAD

**Issue by xjimi** [huangzhibiao/BGFMDB#33]
在 stockModel 裡將 bg_uniqueKeys 移除，會無法再新增相同name的資料
但我在people裡使用 bg_uniqueKeys 可防止重復插入相同name資料
再將 bg_uniqueKeys 移除，也可以再新增相同name的資料

以上這些情況都是發生在已經編譯過之後的再次修改。

在使用 uniqueKeys 是否有編譯順序的差別呢？

**Comment by huangzhibiao** [comment]
都是一样的操作，不过如果唯一约束改变(新增，删除，改变)改变的话，需要调用bg_updateversion:接口刷新一下,具体操作看API说明.

**Comment by xjimi** [comment]
了解~謝謝
