### ISSUE TITLE
可否将数据库放入Library里？

### ISSUE THREAD

**Issue by lylcf** [huangzhibiao/BGFMDB#35]
放在Documents里大部分情况下不会出问题，但如果开发者需要开启app的共享文件夹功能，那么苹果要求Documents里的文件只能是“用户自主下载、导入、创建”的文件，有其他非用户主动产生的文件会被拒审。
以前就遇到过这种情况，百度地图就是把缓存文件方Documents里，导致app新版本开启共享文件夹功能后被拒审，最后得换高德地图，高德地图的缓存文件是放Library里的。

**Comment by huangzhibiao** [comment]
修改BGDB.m里的这个宏即可，CachePath(name)；
