### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Wilson9312** [huangzhibiao/BGFMDB#37]
11.2 iphoneX crash in BGTool.m 913 line "-[__NSDictionaryM containsString:]: unrecognized selector" when -beginTransformAction:

**Comment by Wilson9312** [comment]
![image](https://user-images.githubusercontent.com/17453000/37143727-f6043612-22f6-11e8-979e-7aef694b1d7e.png)

**Comment by huangzhibiao** [comment]
截图我看一下你的类结构.
