### ISSUE TITLE
模型的图片数组存储的bug

### ISSUE THREAD

**Issue by zgs2046** [huangzhibiao/BGFMDB#47]
模型带一个数组，数组中装的是UIImage,存储报错。然后修改成demo中的UIImage经过UIImageJPEGRepresentation处理后，存储可以了，但是取出后，无法显示，打印是NSConcreteData

**Comment by huangzhibiao** [comment]
亲，你存的时候转成了NSData,取出来的时候也会是NSData,你是不是要把Data数据转成image才能显示？！

数组中存图片要转成NSData再存.

**Comment by zgs2046** [comment]
好的，这一点我没有注意到。
