### ISSUE TITLE
关于存json字符串的问题

### ISSUE THREAD

**Issue by ChandHsu** [huangzhibiao/BGFMDB#56]
我存了一个字典转成的json串,取出来变成空了
请问,怎么解决呢

**Comment by huangzhibiao** [comment]
请详细说明，贴出类结构和使用方式.

**Comment by ChandHsu** [comment]
是一级类里面一个userData的字符串,很奇怪,我存个汉字也存不进去,现在json字符串可以存了,但是,我只存一个汉字或者一串其他的,就不能存了,
![image](https://user-images.githubusercontent.com/10771362/39921743-9ddd0fd8-554e-11e8-8622-a91c0385000b.png)

**Comment by ChandHsu** [comment]
我找到了问题,是因为json串取出来和存的时候不一样了,多了些空格和逗号;
另外,我尝试把json转成NSData的description字符串存储,存储是失败的,求教

**Comment by huangzhibiao** [comment]
不可能,不管是什么字符串，你正常存进去，肯定会正常取出来.

**Comment by huangzhibiao** [comment]
或你把问题代码抽取成demo发给我看下.

**Comment by ChandHsu** [comment]
代码没有问题,就是简单存了一个json字符串,我打开了数据库,发现是没有存进去;先看一下数据结构:
![4cec6cea-4717-4a7b-a2a6-48e52ec0c2fa](https://user-images.githubusercontent.com/10771362/39980062-79eb2f4e-577c-11e8-8436-54a935550923.png)
![5495ef7d-a80d-400d-9853-c7f599f44f25](https://user-images.githubusercontent.com/10771362/39980072-8dab29a8-577c-11e8-9d8d-0b3f033fa018.png)
经过测试我发现,把要存到userData的数据转存为messageBody里面的text,就各种正常了,原因不明
