### ISSUE TITLE
大量的调用 bg_saveOrUpdateAsync 时崩溃在 添加操作到线程池

### ISSUE THREAD

**Issue by MQL9011** [huangzhibiao/BGFMDB#79]
![image](https://user-images.githubusercontent.com/11871158/45746517-10bedd80-bc36-11e8-907b-a6b4533b24cc.png)

**Comment by MQL9011** [comment]
这样子增加一个 random
会不会 有 random重复情况,依旧崩溃呢?

**Comment by huangzhibiao** [comment]
[[NSDate new] timeIntervalSince1970]和random()一起配合，基本不会重复了.
