### ISSUE TITLE
pod 查询不到

### ISSUE THREAD

**Issue by wulingf** [huangzhibiao/BGFMDB#9]
pod search BGFMDB
[!] Unable to find a pod with name, author, summary, or description matching `BGFMDB`

**Comment by huangzhibiao** [comment]
pod的缓存问题，清理一下pod缓存，很多人都遇到，不过其他库好像没有这样，我稍后再看一下是不是pod上传那边需要设置什么东西的.

**Comment by huangzhibiao** [comment]
如果pod搜不到最新库的就在终端里执行一下这句：pod repo update更新一下pod缓存就可以了.

**Comment by MikasaAckerman** [comment]
我也不行。。也更新了repo也不行，就把后面的~>1.50去掉就好了~
