### ISSUE TITLE
模型里有方法导致崩溃

### ISSUE THREAD

**Issue by Jayxiang** [huangzhibiao/BGFMDB#91]
模型有几个方法,导致在对象转json字符的地方崩溃了

**Comment by huangzhibiao** [comment]
不是什么类型的对象都能存，不能存的你要自己转换成nsdata类型的存

**Comment by Jayxiang** [comment]
是的, 但是我说的是我在模型里有几个方法,   导致了崩溃.    想问一下能优化一下过滤掉方法吗?

**Comment by huangzhibiao** [comment]
你模型的方法跟库没有关系

**Comment by huangzhibiao** [comment]
库只会扫描的的类字段和库指定的方法，不会去扫描或执行你自己定义的方法

**Comment by Jayxiang** [comment]
en 好的
